Design/15
ECube-Reboot/LiveOn-Reborn-iOS pull request #16
Opened 2022-07-13 06:22 UTC by jinccc97

## 🟣 관련 이슈

#15 

## 🟣 구현/변경 사항 및 이유

- custom font 추가 : 달력뷰의 숫자에 사용되는 폰트(NerkoOne-Regular)와 손글씨용 폰트(나눔손글씨 중학생.ttf) 를 추가하고, 원활히 사용할 수 있도록 Font Extension을 추가했습니다.
- colorExtension 추가 : hex color Extension을 추가하고, 기본 컬러들을 Extension의 static var 로 선언해두었습니다.
## 🟣 PR Point
향후 폰트를 사용하실 경우가 생길테니, fontExtension 확인 후 사용법 숙지하면 좋을 것 같습니다.
! color는 통일성을 위해 asset에 따로 추가보다는 Color+extension파일 내에서 hex 변수 선언해주세용

## 🟣 참고 사항

2022-07-13 10:43 UTC, seongmin221 commented
좋습니다!! 코드는 많이 없지만 쓴 것들 대부분 깔쌈하게 잘 쓰인 것 같군요 ㅎㅎ
그 백로그 보면 공통 컴포넌트 제작도 Task로 있는 것 같은데 이건 추후에 작업 예정이신건가요??
이 브랜치는 머지하고 없애도 되는걸까유

2022-07-13 11:11 UTC, seongmin221 approved these changes
LGTM

제가 reviewer가 안돼있어서 PR 있는곳에 그냥 댓글로 달았슴다..

2022-07-13 12:19 UTC, jinccc97 commented
> LGTM
> 
> 제가 reviewer가 안돼있어서 PR 있는곳에 그냥 댓글로 달았슴다..

엇 그러게요 ㅋㅋ 이번에도 이따네요;.? 추가해두었습니다! ㅎㅎ

2022-07-13 12:20 UTC, jinccc97 commented
> 좋습니다!! 코드는 많이 없지만 쓴 것들 대부분 깔쌈하게 잘 쓰인 것 같군요 ㅎㅎ 그 백로그 보면 공통 컴포넌트 제작도 Task로 있는 것 같은데 이건 추후에 작업 예정이신건가요?? 이 브랜치는 머지하고 없애도 되는걸까유

넵! 컴포넌트는 아직 제작하지 않았습니다. task 따로 빼려구용..! 일단 이 브랜치는 삭제해도 될 것 같습니다. 이슈에서도 task 지울게요!

2022-07-13 14:05 UTC, teethemoji commented on liveOnReboot/liveOn/Resource/Assets.xcassets/GiftBox/addButton.imageset/Contents.json
> +}
+의 세로 획이 아래로 갈수록 왼편으로 쏠려 있어 화면에서 작게 보일때 깔끔해보이지 못하는 것 같습니다. 자주 쓰이는 버튼인지라 수정되는 것이 좋다고 생각되는데 어떠세요?

2022-07-13 14:12 UTC, teethemoji requested changes
+버튼 관련 코멘트만 확인해주세요!

2022-07-13 14:45 UTC, jola7373 approved these changes
LGTM
comment 달고 싶어 열심히 쳐다봤는데 깔끔하네요.

2022-07-14 00:03 UTC, seongmin221 approved these changes
LGTM...
이번엔 그냥 이렇게 넣을게유 ㅎ

2022-07-14 13:03 UTC, italsehf approved these changes
PR 늦게 봐서 미안해요
캘린더뷰 폰트, 크기 생각 못하고 있었는데 챙겨줘서 고마워요
머지 직접 해주셔도 될 거 같아요!

2022-07-15 00:16 UTC, jinccc97 commented on liveOnReboot/liveOn/Resource/Assets.xcassets/GiftBox/addButton.imageset/Contents.json
> +}
넹! 동의합니다 :) 수정 후 머지하도록 하겠습니다!

2022-07-15 00:19 UTC, Rookie0031 approved these changes
고생하셨습니다~

2022-07-15 01:42 UTC, merged