[Refactor] 달력 Refactoring
ECube-Reboot/LiveOn-Reborn-iOS pull request #20
Opened 2022-07-17 15:41 UTC by italsehf

## 🟣 관련 이슈

#12 

## 🟣 구현/변경 사항 및 이유

- 기존에 사용하였던 Calendar 코드 Refactoring
- Refactoring을 할 때 MVVM 구조에 맞게 폴더링
- 지금 당장 할 수 있는 약간의 UI 수정

## 🟣 PR Point

- Calendar 관련 파일들이 알맞은 폴더링 구조에 위치하고 있는지 확인 부탁드립니다. 
- Calendar에 들어가는 몇몇 함수들을 Extension으로 분리하였는데 이 부분이 ViewModel에 들어가는 것이 맞는 지 헷갈립니다.

## 🟣 참고 사항

중간중간에 Test용으로 들어가있는 코드 및 주석 처리 되어있는 코드가 있을텐데 그 부분은 추후 수정 예정이니 크게 신경쓰지 않으셔도 됩니다.

2022-07-18 14:57 UTC, seongmin221 reviewed
고생 많으셨습니다..!!
오늘 하루랑 잠깐 이야기했는데 calender가 진짜 세상에서 제일 어렵다고 하네요 ㅎㅎ...
소올직히 막 이해가 되진 않았지만 좀 더 깔끔한 코드가 될 수 있는 방향으로 리뷰해봤습니다

- 민도 루키의 PR과 같이 조금 더 단위를 나눠주셔도 될 것 같아요! 파일 개수는 최대 10개, 코드 바꾼건 최대 300줄로 하면 어떨까요? 이건 팀 내에서 이야기 해봅시다!

수고많으셨어요!!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +    func CardView(value: CalendarModel)->some View {
p3;
띄어쓰기 부탁드립니다..!
```swift
func CardView(value: CalendarModel) -> some View {
```

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +
p3;
필요 없는 띄어쓰기는 없애주세요!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +
p3;
여기도 필요없는 띄어쓰기라 생각합니다..!!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +            in
p2;
요놈 원래 띄어있는게 맞나요??!
```swift
var days = currentMonth.getAllDates().compactMap { date -> CalendarModel in
```
요런 모양이지 않나요?!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Extensions/Date+Extension.swift
> +
p3;
요기도 필요없는 띄어쓰기라 생각됩니다!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Model/Calendar/CalendarModel.swift
> +    var id = UUID().uuidString
Q. UUID()에 .uuidString을 붙인 이유는 뭔가요??!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +    }
아직 조금 아리까리한데 여기에서 굳이 init을 쓸 필요가 있을까요??
```swift
@Published var list: [UpcomingEventsModel] = []
```
이런 모양은 어떨까요?

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +    }
제가 말한게 다 정답은 아니므로...
이후에 init이 필요하실 것 같다고 생각된다면 제 의견 기각시켜도 괜찮습니다^^

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Calendar/AddUpcomingEventView.swift
> +    @State private var showani = false
p3;
CamelCase 적용해주시면 감사하겠습니다!
그리고 ani가 animation의 약자인가요??!
좀 더 풀어서 쓰셔도 괜찮을 것 같아유!! showAnimation 이런식으루요!!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                            ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
p3;
굳이 띄어쓰신 이유가 혹시 있을까요??

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +
p3;
줄바꿈은 하나만 사용해도 충분할 것 같습니다!

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +
어느게 어려운건지 조금 더 자세히 적어주시면 도움을 드릴 수도....????
또는 이슈로 파보는것도 하나의 방법이라 생각합니다😉

2022-07-18 14:57 UTC, seongmin221 commented on liveOnReboot/liveOn/ViewModel/Calendar/DateToStringUpcomingEventsViewModel.swift
> +    dateFormatter.dateFormat = "MM/dd"
p3;
요 가운데에 줄바꿈은 없어도 되지 않을까 싶습니다!

2022-07-18 15:09 UTC, italsehf commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +    func CardView(value: CalendarModel)->some View {
넵 수정사항 반영하겠습니다~

2022-07-18 15:11 UTC, italsehf commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +
제가 눈이 침침해서...수정할게요 껄껄

2022-07-18 15:11 UTC, italsehf commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +
수정해오기...

2022-07-18 15:11 UTC, italsehf commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +            in
맞아요 원래 그 모양인데 왜 저렇게 되어 있는건지 금차차;;

2022-07-18 15:12 UTC, italsehf commented on liveOnReboot/liveOn/Extensions/Date+Extension.swift
> +
확인 ^^

2022-07-18 15:12 UTC, italsehf commented on liveOnReboot/liveOn/Model/Calendar/CalendarModel.swift
> +    var id = UUID().uuidString
이 부분은 제가 취약해서 공부한 후에 다시 코멘트 달겠습니다!!

2022-07-18 15:13 UTC, italsehf commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +    }
이 부분은 밀센세랑 같이 코드 작성하였는데 밀센세한테 물어볼 필요가 있겠네요

2022-07-18 15:14 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/AddUpcomingEventView.swift
> +    @State private var showani = false
animation의 약자 맞아요!! showAnimation으로 수정할게요 ~

2022-07-18 15:14 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                            ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
아무래도 저 혼자만의 가독성 해결을 위해 저렇게 해놓은 거 같네😅

2022-07-18 15:15 UTC, italsehf commented on liveOnReboot/liveOn/ViewModel/Calendar/DateToStringUpcomingEventsViewModel.swift
> +    dateFormatter.dateFormat = "MM/dd"
수정사항 반영하겠습니다 !

2022-07-18 15:16 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +
View 파일 안에 func이 있을 필요가 없다는 생각이 들어서 분리하고 싶었던 부분이였는데 좀더 시도해보고 정 안되겠으면 이슈로 추가해놓을게요 !!

2022-07-18 15:49 UTC, Rookie0031 requested changes
### 민턴 캘린더뷰 수고했습니다!!!!
아래는 저의 코드리뷰 컨벤션입니다

## Review Convention

Request: 고쳐야 approve 해드립니다.

Suggest: 제 생각에 이러면 좋을 거 같습니다. (안고쳐도 그만)

Question: 저도 잘 몰라서 쓰신 의도가 궁금합니다.

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                            let days: [String] =
## Request
Stack 내부는 컨텐츠가 담기는 자리로 변수나 상수를 내부에서 선언하는게 불필요하다고 생각됩니다!
days 배열을 CalendarModel 파일로 그냥 옮기거나 가능하다면 enum 형식으로 선언하고 CaseIterable을 사용해서 ForEach 안에서 쓰는게 좋을거같습니다!

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                                    withAnimation {
## Question
버튼 부분에 withAnimation은 어떤 역할인가요??

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                                        showDatePicker.toggle()
## Question
클릭하면 데이트피커가 보여지는거라서 둘다 기능이 같다고 생각했는데 showDatePicker와 isClicked 의 차이가 뭔가요??

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                PopupDateView(popupDate: self.currentDate,
## Question
showDatePicker, isClicked, popUpBoolean 모두가 데이트 피커를 띄우고 취소하는 Boolean인 거 같은데 추후에 각각이 필요해서 일단 선언해놓은건가요??

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +
네넵 어떤 부분에서 막혔는지 이슈로 남기거나 회의때 이야기하면 좋을거같아요!

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +    func CardView(value: CalendarModel)->some View {
## Question
CardView는 그냥 View 프로토콜을 따르는 구조체로 만들어도 될 거 같은데 함수로 빼서 viewBuilder를 사용한 이유가 있나요?? 
근데 뭔가 코드가 복잡해보여서 건드리기보단 그대로 사용해도 될 거 같긴합니다.

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +class EventStore: ObservableObject {
## Request
EventStore는  유저가 입력한 데이터에 따라 캘린더뷰를 업데이트 하는데 영향을 주는 클래스입니다.
그래서 Model보다는 ViewModel에 넣는게 적절해보입니다!

2022-07-18 15:49 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/PopupDateView.swift
> +    @Binding var currentDate: Date
## Suggest
이 부분에서 Binding이 3개가 되어있는데 불필요한 불리언 변수가 있는지 한번 체크해보는게 좋을거같습니다!!

2022-07-19 00:03 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                            let days: [String] =
넵 한번 도전해보겠습니다 !

2022-07-19 00:09 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                                        showDatePicker.toggle()
클릭하면 데이트피커가 보여지게 해주는 역할은 showDatePicker이고 isClicked는 블러 효과를 넣기 위해서 변화를 구분하기 위해 들어가있다고 생각해주시면 될 거 같습니다!

2022-07-19 00:14 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                                    withAnimation {
버튼이 눌리게 되면 잠깐 하애졌다가 다시 원래대로 돌아오는 애니메이션 역할을 합니다.

2022-07-19 00:15 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                PopupDateView(popupDate: self.currentDate,
일단 따로 구분지어서 선언하는 것이 충돌이 일어나지 않을 것이라고 생각해서 각각 선언해놓았습니다!

2022-07-19 00:16 UTC, italsehf commented on liveOnReboot/liveOn/Extensions/Calendar+Extension.swift
> +    func CardView(value: CalendarModel)->some View {
이 부분은 동영상을 따라서 적은 코드인데 루키 말대로 구조체로 따로 만들어 볼려고 해보았지만 실패해서 그대로 두었습니다...

2022-07-19 00:17 UTC, italsehf commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +class EventStore: ObservableObject {
수정사항 반영하겠습니다 ~

2022-07-19 00:18 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/PopupDateView.swift
> +    @Binding var currentDate: Date
한번 체크해보겠습니다😄

2022-07-25 11:15 UTC, jinccc97 reviewed
캘린더 마-스-타가 되어가는 여정 잘 보았습니다!
가독성 면에 있어 커밋하실 때 단위를 조금 나누어 해주시면 좋을 것 같습니다!
정말 고생많으셨어요! 굳굳 👍

2022-07-25 11:15 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +    }
왜냐면 class 안에 선언되어있기 떄문입니다! 생성자가 필수죵

2022-07-25 11:15 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Calendar/AddUpcomingEventView.swift
> +    @State private var showani = false
약자는 지양해주세용, 또한 카멜케이스 컨벤션도 꼭꼭 지켜주세용

2022-07-25 11:15 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Calendar/CalendarModel.swift
> +struct CalendarModel: Identifiable {
모델의 경우 파일이름에 Model을 붙이지 않기로 했던 것 같습니다! 다른 팀원분들 맞나용?

2022-07-25 11:15 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Calendar/AddUpcomingEventView.swift
> +            .padding([.trailing, .leading], 15)
이 부분을 
var header: some View {
 //하이라이트한 내용 덩어리 전체
}
로 아래에 따로 선언해주면 더 가독성이 좋아져요!

2022-07-25 11:15 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                            ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
이드님 굳의 주의보🟨 드립니다.

2022-07-25 11:15 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +        guard let currentMonth = calendar.date(byAdding: .month, value: (isUp ? 1 : -1), to: self.currentDate)
` value: (isUp ? 1 : -1)`

이건 어떤 역할을 하는 친구인가요?

2022-07-25 11:15 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Calendar/UpcomingEventsView.swift
> +    let event : UpcomingEventsModel
세미콜론은 뒤에만 띄어쓰기를 쓰는게 일반적이에요!

```suggestion
    let event: UpcomingEventsModel
```

2022-07-25 14:19 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/AddUpcomingEventView.swift
> +            .padding([.trailing, .leading], 15)
가독성을 위해서 바로 개선해보겠습니다 ~!

2022-07-25 14:20 UTC, italsehf commented on liveOnReboot/liveOn/Model/Calendar/CalendarModel.swift
> +struct CalendarModel: Identifiable {
@seongmin221 @Rookie0031 @teethemoji 모델의 경우 파일 이름에 Model 안 붙이는 거 맞나요 ~?

2022-07-25 14:21 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/UpcomingEventsView.swift
> +    let event : UpcomingEventsModel
오늘도 한 가지 배웠습니다 밀 센세..

2022-07-25 14:23 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +        guard let currentMonth = calendar.date(byAdding: .month, value: (isUp ? 1 : -1), to: self.currentDate)
달력에서 이전 월 / 다음 월 로 이동할 때 쓰는 친구입니다 !!

2022-07-25 14:29 UTC, Rookie0031 commented on liveOnReboot/liveOn/Model/Calendar/CalendarModel.swift
> +struct CalendarModel: Identifiable {
그랫었던 거 같은데, 맨 처음 폴더파고 기본으로 세팅된 파일명들은 뒤에 Model이 붙어있네요?? 
ex. LogInModel 그리고 이드도 Model을 붙여서 만들어놨어요 (VoiceMail) 
왜 저런이야기가 나왔는지 기억은 잘 안나지만, 어떤 부분이 가독성이 더 좋은지 이야기해볼 필요는 잇을거같네요 캘린더는 캘린더모델을 많이 쓰나요??

2022-08-02 07:16 UTC, italsehf commented on liveOnReboot/liveOn/Model/Calendar/CalendarModel.swift
> +struct CalendarModel: Identifiable {
늦게 코멘트 남겨 고멘..
캘린더에서는 캘린더모델을 캘린더를 만드는 데에 필요한 함수에서만 사용하고 있습니다.
개인적인 의견을 남기자면 뒤에 Model이나 ViewModel을 남겨놓는 것이 파일명이 길어지더라도
어떤 파일인지 한번에 알 수 있어 좋을 거 같습니다!

2022-08-03 14:41 UTC, Rookie0031 approved these changes
### 감사합니다!!!

캘린더뷰에 총 8개 변수가 바인딩되어잇네요 그것도 4개씩 두개의 뷰에 나눠서... 코드가 훨씬 정리잘되고 읽기도 좋아진거같아여 좋습니다. 이제 UI 정리하면서 API 같이 엮으면 되겟네여

아주 자잘한 코멘트 남겨놓았으니 그것만 답변주시고 머지 진행하시면 될 거 같습니다 굿

2022-08-03 14:41 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                                        upcomingEventTitle = ""
## Question
여기서 이벤트타이틀과 메모를 초기화하는 이유가 뭔가여?? UpcomingEventView에 엮여있는 애들을 초기화하는 용도???

2022-08-03 14:41 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/PopupDateView.swift
> +    @State var popupDate: Date = Date()
## Suggest
아주아주아주 사소한 것이지만 popUpDate로 고치면 좋을거같습니다 하하하

2022-08-03 14:41 UTC, Rookie0031 commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +    let id: UUID
## Question
다가오는 기념일의 데이터 모델에 Identifiable이 필요한 이유가 무엇인가여???

2022-08-03 14:41 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Calendar/UpcomingEventsView.swift
> +// Test용으로 넣어 놓은거고 UI에 맞게 수정할 예정
이제 메모랑 타이틀만 연동하면 되겟군요 굳...

2022-08-04 06:44 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/CalendarView.swift
> +                                        upcomingEventTitle = ""
역시 루키.. UpcomingEventsView에 엮여있는 변수들 값을 초기화하여 행여나 이전 값이 불러와지는 걸 방지하기 위해서입니다 !

2022-08-04 06:45 UTC, italsehf commented on liveOnReboot/liveOn/View/Calendar/PopupDateView.swift
> +    @State var popupDate: Date = Date()
수정하였습니다 루하하하

2022-08-04 06:51 UTC, italsehf commented on liveOnReboot/liveOn/Model/Calendar/UpcomingEventsModel.swift
> +    let id: UUID
UpcomingEvent를 생성할 때 Identifiable로 선언할 경우 기념일마다 id가 부여되어 각각의 기념일을 구분하고 식별할 수 있게 되기 때문입니다!

2022-08-04 06:52 UTC, merged