[Feat & Setting] 쪽지 선물 생성 뷰 제작 및 Extension 정비
ECube-Reboot/LiveOn-Reborn-iOS pull request #26
Opened 2022-07-26 12:29 UTC by jinccc97

## 🟣 관련 이슈
#25 

## 🟣 구현/변경 사항 및 이유
- 쪽지 만드는뷰를 제작했습니다.
- 글자수 표시 레이블의 경우, 다른 뷰에서도 사용될듯 해 modifier extension에 생성해두었습니다. 점찍어서 활용하세요
<img width="470" alt="스크린샷 2022-07-26 오후 9 23 23" src="https://user-images.githubusercontent.com/61951603/181004874-2776f744-1765-465b-9c10-f71cb1b401e9.png">
- textEditor에 글자수 제한은 letterView에서만 쓸 것 같아 따로 빼지 않았습니다. 또한 기존의 Util-TextLimitter는 삭제하였습니다.(작동안했음)
- ColorExtension의 경우 중복되거나, ColorAsset을 사용하는 요소도 있어 삭제했습니다. 그 결과 루키의 코드를 일부 수정하게되었습니다.
- 

## 🟣 PR Point
- 기존것을 옮기되 refactor 진행하였습니다.
- 이제 서버와 연동할 예정입니다. 기존에는 서버 연동 X 그냥 배열에 쌓이는 식이었는데 서버 연동이 되며 기존 코드가 날라갑니다.
- Literal을 생성했습니다. placeHolder 문구, 글자 제한 숫자(Int)를 따로 빼서 관리해둡시다. 21776c86de87e2fcc0412f4135ff64afa7b059e4
-
## 🟣 참고 사항

2022-07-30 12:55 UTC, Rookie0031 requested changes
### 고생햇습니다 ^_^

전반적으로 신경써서 잘 수정해준거 같습니다. 몇가지 요청사항과 질문들을 남겨놓앗습니다 굿굿

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +//  Created by Keum MinSeok on 2022/07/09.
## Suggest 
여기 금민 말고 밀부 이름으로 바꾸면 좋을거같습니다 ㅋㅋㅋㅋ 나중에 수정할 때 누가한건지 바로 볼 수 있더라구요!!

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +  private var id = UUID()
## Question
편지 모델에 UUID와 sender가 있는데요, 처음에 볼 때는 UUID로 보내는 사람 구분하는 줄 알앗는데 둘의 역할이 뭔가요??

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/Util/Literal/textLimit.swift
> +  static var nickName: Int { return 10 }
enum으로 잘빼신거같습니다. 저도 사진선물할 때 텍스트 같이 보내는데 여기 추가한다음 써먹으면 되겠네요 떙큐

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterView.swift
> +                                withAnimation() {
애니메이션 의도하고 넣으신건가요?? 디테일이 굿이네요

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/Extensions/Text+Extension.swift
> +    func letterCountSyle() -> some View {
## Question
letterCountStyle에서 t가 빠진거죠???

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterView.swift
> +            .background(Image(letterStyle ?? "letter_green").resizable().shadow(color: Color(uiColor: .systemGray4), radius: 4, x: 1, y: 3))
## Question
여기 결국에 letter_green이라는 이미지를 배경에 넣는거죠?? 상단에 선언된 letterStyle 변수가 여기만 쓰이는거같은데 옵셔널로 선언해놓고 값을 안주게하는 방식으로 해놓은 이유가 있나요?? 제 생각엔 걍 Image("letter_green") 하면 될거같은데요??

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/ViewModel/Gift/Letter/LetterViewModel.swift
> +                    source.wrappedValue = newValue
## Suggest
앱 빌드시 이런 에러를 발견했는데 혹시 큰 문제안되는걸까요?? 수정가능하다면 수정요청드립니다!!

<img width="836" alt="image" src="https://user-images.githubusercontent.com/103009135/181914974-35a45e10-fcd2-413f-bbea-762583c3cb7e.png">

2022-07-30 12:55 UTC, Rookie0031 commented on liveOnReboot/liveOn/ViewModel/Gift/Letter/LetterViewModel.swift
> +public extension Binding where Value: Equatable {
## Question
이 부분 코드가 좀 깔삼한거같습니다. 잘 이해는 안되지만 textEditor 글자수가 없을 때 다시 플레이스 홀더를 배치하기 위한 구조의 일부로 생각되는데 맞나요?? 이 코드짜실 때 참고했던 자료 있다면 링크좀 부탁드리겠습니다!

2022-08-07 06:11 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +//  Created by Keum MinSeok on 2022/07/09.
올 민돌녀석 바로 삭제.

2022-08-07 06:12 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +  private var id = UUID()
음 UUID는 쪽지 한 개체 자체의 식별값이고, sender는 정말 커플 둘 중 누가 보냈는지 구분하는 용도 입니다!

2022-08-07 06:12 UTC, jinccc97 commented on liveOnReboot/liveOn/Util/Literal/textLimit.swift
> +  static var nickName: Int { return 10 }
키윽 쁘듯

2022-08-07 06:12 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterView.swift
> +                                withAnimation() {
네 ^ㅇ^

2022-08-07 06:13 UTC, jinccc97 commented on liveOnReboot/liveOn/Extensions/Text+Extension.swift
> +    func letterCountSyle() -> some View {
오......이걸 보네

2022-08-07 06:13 UTC, italsehf commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +//  Created by Keum MinSeok on 2022/07/09.
녀석이란 말은 빼주세요 ^^

2022-08-07 06:20 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +//  Created by Keum MinSeok on 2022/07/09.
2006eccc1d20c48ee70e9eb9df73f400b2c2c5d5

2022-08-07 06:20 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +//  Created by Keum MinSeok on 2022/07/09.
2006eccc1d20c48ee70e9eb9df73f400b2c2c5d5

2022-08-07 06:28 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterView.swift
> +            .background(Image(letterStyle ?? "letter_green").resizable().shadow(color: Color(uiColor: .systemGray4), radius: 4, x: 1, y: 3))
아 이거 원래 부분에서 옮기면서 생성부를 놓쳤는데요, 원래는 랜덤으로 쪽지 색이 정해지게 하려던 참이었습니다. 이부분은 우선 제안해주신대로 수정후 향후 모델까지 함께 수정해봐야겠어요.

2022-08-07 06:33 UTC, jinccc97 commented on liveOnReboot/liveOn/ViewModel/Gift/Letter/LetterViewModel.swift
> +                    source.wrappedValue = newValue
제 환경에서는 해당 에러가 발생하지 않는데요, 모르겠네용 ㅠㅠ

2022-08-07 06:34 UTC, jinccc97 commented on liveOnReboot/liveOn/ViewModel/Gift/Letter/LetterViewModel.swift
> +public extension Binding where Value: Equatable {
네 맞습니다!
https://developer.apple.com/forums/thread/124880
위 링크를 참고했습니다!

2022-08-07 11:12 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +//  Created by Keum MinSeok on 2022/07/09.
> 녀석이란 말은 빼주세요 ^^

반영해드렸습니다 ^^

2022-08-07 23:00 UTC, Rookie0031 approved these changes
컨플릭 해결하고 머지하면 될 거 같습니다 굿굿
근데 letterList브랜치가 이 브랜치 내용을 포함하고 있으면 결국 이 PR은 필요없는건가요? 알아서 잘 머지하시길^^

2022-08-08 06:51 UTC, closed without merging