Feature/11 send picture gift to server
ECube-Reboot/LiveOn-Reborn-iOS pull request #31
Opened 2022-08-19 03:58 UTC by Rookie0031

## 🟣 관련 이슈
#11 (사진선물보내기)

## 🟣 구현/변경 사항 및 이유
1. 사진 선물 보낼 때 한줄 편지 기능 추가 + 서버 연동
2. 서버 통신 코드에서 강제언래핑 삭제 (if let 사용) + JPEG, PNG 사진 데이터 처리 코드 추가
3. 한줄 편지 글자수 제한 및 제한 글자수 초과시 간단한 animation 추가

## 🟣 PR Point
#### 불필요한 변수나 코드가 있는지 중점적으로 체크해주시면 감사하겠습니다.
#### 잘못사용된 문법들이 있는지 궁금합니다 
#### 다른 방법이나 문법을 썼다면 더 가독성있고 깔끔한 코드가 되었을 거 같은 부분에 자유롭게 피드백 주시면 감사하겠습니다. 

## 🟣 참고 사항
### 사진 + 한줄 편지 선물하기
https://user-images.githubusercontent.com/103009135/185539365-174bc783-e00a-4ec0-87fb-adaf511eab91.mov

### Status Code 200 확인
<img width="702" alt="image" src="https://user-images.githubusercontent.com/103009135/185539263-3a147efc-6aab-47f1-8ae0-20f77e3a6b72.png">

2022-08-19 05:31 UTC, jinccc97 requested changes
좀 더 깔끔한 코드를 위한 제안사항 몇가지 담았습니다.
전반적으로 깔끔하게 작성하려는 노력이 보였어요. 수고하셨습니다! 👍👍👍👍

2022-08-19 05:31 UTC, jinccc97 commented on liveOnReboot/liveOn/Network/Gift/Picture/EndPoint/PictureEndPoint.swift
> +            if !imageDataJPEG!.isEmpty {
p2;
not과 언래핑 기호가 같이 있어 혼란을 줍니다.
 isEmpty를 점검하고, 아래에서도 imageData를 활용하니, 매번 가져와서 언래핑하는 것보다
if let 구문이나 guard 구문을 활용하는 것이 더 깔끔할 것 같아요!

2022-08-19 05:31 UTC, jinccc97 commented on liveOnReboot/liveOn/Network/Gift/Picture/EndPoint/PictureEndPoint.swift
> +            let imageDataPNG = polaroid.pngData()
Question;
png와 jpeg 확장자 둘 다 고려하는 이유가 궁금합니다!

2022-08-19 05:31 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +        moyaService.request(.imagePost(comment: comment, polaroid: pictureModel.image ?? UIImage())) { response in
p3;
.앞에는 공백을 하나 띄우는 것이 맞지 않나용!?

2022-08-19 05:31 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +                    print("response는 다음과 같습니다. \(result)")
p2;
이 부분은 향후 출시를 가정했을 때 데이터가 샐 수 있는 부분이라 구현이 완료되었다면 로그 print는 삭제해주는 것이 좋다고 합니다!

2022-08-19 05:31 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +        .background(Color.background)
p1;
`.backgroundGray`를 사용해주세요. 
background는 컬러에셋기반인데 현재 컬러 에셋을 사용하고 있지 않기도하고, 기본 background하고 이름이 겹쳐 원하는 결과가 나오지 않습니다!
그리고 ColorExtension 파일에 정의된 let background는 **삭제**부탁드리겠습니다!

2022-08-19 05:31 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                              }
## Request
p1;
foregroundColor(.textBodyColor) 적용부탁드립니다!

2022-08-19 05:31 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                                  }
## Request
p1;
이 부분 로딩이미지 보여주려고 일부러 시간을 추가한 것으로 기억합니다. 
timer보다는 확실한 방법으로 서버 통신이 끝난 후 작동하는 `completion handler`를 활용하는 것이 더 좋을 것 같습니다!
이 부분은 제가 시험삼아 한 번 만들어봤는데 잘 작동하네요 ㅎ 
원하시면 제가 이 브랜치에 테스팅 버전을 커밋해볼게요(향후 제대로 로딩 이미지 넣을 예정)
![ezgif-3-2eb408e2f1](https://user-images.githubusercontent.com/61951603/185549072-4da73e7a-f363-45a2-a4dd-f40d5ee7e5a7.gif)

2022-08-19 05:41 UTC, Rookie0031 commented on liveOnReboot/liveOn/Network/Gift/Picture/EndPoint/PictureEndPoint.swift
> +            if !imageDataJPEG!.isEmpty {
아 이 부분은 제가 처음에 이렇게 바꿧다가 말씀해주신 대로 if let으로 처리해두었습니다
그래서 최종본에는 if let으로 담겨있습니다 https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/31/commits/947b616e72555d57b6ec6c2c9cabb9f1534cdfe6
<img width="960" alt="image" src="https://user-images.githubusercontent.com/103009135/185550866-ada31775-0efd-414f-9afa-e663c9bc005d.png">

2022-08-19 05:45 UTC, Rookie0031 commented on liveOnReboot/liveOn/Network/Gift/Picture/EndPoint/PictureEndPoint.swift
> +            let imageDataPNG = polaroid.pngData()
기존 코드가 png만 처리하는 코드였는데 테스트 결과 jpeg 사진은 에러가 났습니다(status code 500). 그래서 둘다 고려하게 되었습니다.

우선적으로 jpegData로 변환시키는데, 이유는 용량크기가 작기 때문입니다. (손실 압축 기법 표준이라는데 https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/31/commits/947b616e72555d57b6ec6c2c9cabb9f1534cdfe6 이 글을 참고했습니다)
만약 jpeg 변환이 실패해서 nil이 나오면 png로 변환해서 처리합니다

2022-08-19 05:46 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +        moyaService.request(.imagePost(comment: comment, polaroid: pictureModel.image ?? UIImage())) { response in
오 처음 듣는데 어떤 컨벤션을 따르는건가요??

2022-08-19 05:51 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +                    print("response는 다음과 같습니다. \(result)")
반영했습니다~
a993b7c4d11bcf524d03a733f85e31a0e4fb79a1

2022-08-19 05:53 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                                  }
오 좋네요 커밋해주시면 감사하겟습니다 ㅎㅎㅎㅎㅎㅎ

2022-08-19 05:55 UTC, Rookie0031 commented
> 좀 더 깔끔한 코드, 통일성을 위한 제안사항 몇가지 담았습니다.
> 전반적으로 깔끔하게 작성하려는 노력이 보였어요. 수고하셨습니다! 👍👍👍👍

Color 관련된 부분(textBodyColor, backGroundGray) 은 그 컬러를 사용하면 이상하게 에러가 나서 에러가 안나는 부분으로 임시적으로 대체되었는데 한번 수정하고 커멘트남길게용

2022-08-19 05:56 UTC, teethemoji commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                              }
PR 내용에 첨부된 영상에는 .textBodyColor가 적용되어 있는데 왜 삭제하셨나요

2022-08-19 06:21 UTC, jinccc97 commented on liveOnReboot/liveOn/Network/Gift/Picture/EndPoint/PictureEndPoint.swift
> +            if !imageDataJPEG!.isEmpty {
올 굳

2022-08-19 06:21 UTC, jinccc97 commented on liveOnReboot/liveOn/Network/Gift/Picture/EndPoint/PictureEndPoint.swift
> +            let imageDataPNG = polaroid.pngData()
오호 친절답변 감사합니다!!

2022-08-19 06:24 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +        moyaService.request(.imagePost(comment: comment, polaroid: pictureModel.image ?? UIImage())) { response in
그러게욧..

2022-08-19 06:30 UTC, teethemoji commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                                  Image(uiImage: image)
p2;
```suggestion
                                Image(uiImage: selectedImage)
```
그냥 image라고 하기 보다는 selectedImage라고 하는 것이 더 명확할것 같습니다

2022-08-19 06:41 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                                  }
https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/31/commits/4662ec4d2cd63be1e22da0849bd42fd3e5650509

Struct loadingView는 추후 다른 곳에 이동시켜놓을게요~

2022-08-19 07:22 UTC, teethemoji approved these changes
수고하셨습니다

2022-08-19 07:58 UTC, seongmin221 reviewed
굳 좋습니다아
근데 들여쓰기 바뀌는 부분이 가끔씩 있는 것 같네요..!
이게 지난번에 밀 PR에도 그랬는데 왜그런지 모르겠어용 한번씩 고쳐주면 좋을 것 같아요

2022-08-19 07:58 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>      @Environment(\.dismiss) private var dismiss
p5;
@Environment 을 맨 위로 올리는건 어떨까요 ㅎㅋ

2022-08-19 07:58 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +                    //.blur(radius: showLoading ? 6 : 0)
p1;
사용 안하는 주석은 삭제해주세요오

2022-08-19 07:58 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +        moyaService.request(.imagePost(comment: comment, polaroid: pictureModel.image ?? UIImage())) { response in
오잉 요거 뭐가 문제인거죵

2022-08-19 07:58 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +            case .success(_):
저도 이거 좀 애매한데 그냥 .success만 써도 되지 않나요??
(_) 이거 없애구요..!

2022-08-19 10:29 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                                  }
## LGTM
이스케이핑 클로저 상당히 굿굿굿...

## Suggest & Question
1. loadingView 구조체 대문자로 바꿔주세요!
2. imagePost 이후 전송완료 print문은 디버깅용으로 일단 남겨놧나요??

2022-08-19 10:29 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                                  Image(uiImage: image)
좋습니다 반영했습니다!  e45292d555de8ddabb40ed422a63140b95c02752

2022-08-19 10:30 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>      @Environment(\.dismiss) private var dismiss
반영했습니다 ㅋㅋㅋ state로 시작되는 애들끼리 묶는게 더 보기 이쁘네요 굿

2022-08-19 10:30 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +                    //.blur(radius: showLoading ? 6 : 0)
반영완료

2022-08-19 10:31 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +            case .success(_):
.success만 써도 됩니다. 반영완료 ㅎㅋ

2022-08-19 10:52 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
> +        .background(Color.background)
반영완료 099c1a30682db87437918210593ef4eb55a99362

2022-08-19 10:52 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendPicture/SendPictureView.swift
>                              }
반영완료 099c1a30682db87437918210593ef4eb55a99362

2022-08-20 03:31 UTC, jinccc97 approved these changes
크 반영하느라 수고많으셨습니다!!

2022-08-22 00:37 UTC, merged

2022-08-22 04:12 UTC, seongmin221 reviewed
좋습니당~