[Refactor] 쪽지 Api 업데이트 반영
ECube-Reboot/LiveOn-Reborn-iOS pull request #32
Opened 2022-08-19 11:33 UTC by jinccc97

## 🟣 관련 이슈
#25 

## 🟣 구현/변경 사항 및 이유
- 쪽지 색까지 서버에 함께 저장하는 식으로 api 업데이트 반영
- 랜덤 컬러 지정 후 POST
- GET 할 때 color property 추가

## 🟣 참고 사항
<b>
![simulator_screenshot_12B47F77-7A65-4EAA-B050-4459E21D1ABF](https://user-images.githubusercontent.com/61951603/185609473-9e3bf2f8-01a2-4a0c-b5cc-fdeb528282aa.png)
![simulator_screenshot_66C7ABF0-4E91-48B7-AC01-FC582BDDD37A](https://user-images.githubusercontent.com/61951603/185609542-be928020-0bd1-47de-a68f-e891894beb7d.png)

</b>

2022-08-21 10:08 UTC, italsehf approved these changes
휴가기간임에도 불구하고 개발을 하다니..역시 밀리 최고 ~!
뭔가 더 많은 리뷰를 적고 싶었지만 저의 부족한 실력으로 인해
간단한 코멘트 하나 남기고 도망갑니다👏🏻

2022-08-21 10:12 UTC, italsehf commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
> +                        }
p3
들여쓰기가 이상한 거 같은데 한번 확인 부탁드려요~

2022-08-21 11:51 UTC, jola7373 approved these changes
수고많으셨습니다!

2022-08-21 11:51 UTC, jola7373 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +    var color: String = "color_white"
p5
궁금한것이 있습니다
그 color_white를 디폴트로 뒀다가 나중에 onAppear 될때 random에서 가져오는 건가요?
그래서 color의 디폴트가 흰색인가욥?

2022-08-22 00:42 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Gift/Letter/Letter.swift
> +    var color: String = "color_white"
네 맞읍니다! 뷰..에서 하는게 좀 이상하긴 하네요 ..

2022-08-22 05:11 UTC, Rookie0031 requested changes
## 고생하셨습니다!!!!!!!!
#### 폭풍 PR 감사합니다

2022-08-22 05:11 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
>      @State var selectedLetter: LetterGet?
## p1;
#### State private var로 바꿔주세요!
State 프로퍼티 래퍼는 private으로 선언해주는 것이 국룰인 것으로 알고 있습니다. 자세한 이유는 모르지만 안그러면 SwiftUI에서 데이관리에 문제가 생기는 일이 발생할 수 있다고 하네요
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/103009135/185841096-cafac97a-7404-4997-8e62-1324240c2acf.png">

## Reference
https://developer.apple.com/documentation/swiftui/state

2022-08-22 05:11 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
> +                        let columns = Array(repeating: GridItem(.adaptive(minimum: 300), spacing: 1, alignment: .center), count: 2)
## p2;
특별히 Stack안에서 상수/변수를 선언한 이유가 있을까요??? ( let columns 부분)
Stack안에는 Struct만 딱 담겨있고 뷰를 그리는데 필요한 변수,상수는 body 위에 정의하는게 더 깔끔한거 같습니다!!

2022-08-22 05:11 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
> +                         //   .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
## p3
주석은 삭제 ㄱㄱ?

2022-08-22 05:11 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
> +                    ProgressView()
## LGTM
completion handler로 progressView 관리하는거좋네요

2022-08-22 05:11 UTC, Rookie0031 commented on liveOnReboot/liveOn/Util/Literal/letterColorStyle.swift
> +enum LetterColorStyle {
## p5
얘는 그냥 배열인데 왜 enum으로 관리하나요???
간단히 var letters: [String] 이런식으로 사용할 수 있는데 enum으로하면 좋은점이있나요??

2022-08-22 05:11 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SendGift/SendLetter/SendLetterView.swift
> +        if let randomColor = LetterColorStyle.letterColors.randomElement() {
## p5
여기를 if let으로 처리한 이유가 있을까요??? letterColor에 값이 다 들어있어서 nil이 나올 일은 없을거같아서 궁금하네여

2022-08-22 13:02 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
>      @State var selectedLetter: LetterGet?
오.. 좋은거 배워갑니다. 수정완료했어용
1ddb2f1d4a5330c43d2150cda36712de05fe6542

2022-08-22 13:05 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
> +                        let columns = Array(repeating: GridItem(.adaptive(minimum: 300), spacing: 1, alignment: .center), count: 2)
저  컬럼은 if 절을 만족시켜서 들어오지 않는 이상 필요없어서 저기 넣는게 더 깔끔하지 않을까했는데 확실히 상수는 body위가 낫겠네용 수정하겠습니다.
d2400b9ea3ee28cf762f1081e1fa366705847304

2022-08-22 13:06 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/Letter/LetterListView.swift
> +                         //   .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
82d333de14f471ef9286f7edc25aa1d9e3c60f42

2022-08-22 13:10 UTC, jinccc97 commented on liveOnReboot/liveOn/Util/Literal/letterColorStyle.swift
> +enum LetterColorStyle {
어 그러게요..?

2022-08-22 13:13 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SendGift/SendLetter/SendLetterView.swift
> +        if let randomColor = LetterColorStyle.letterColors.randomElement() {
왜냐하면 randomElement 라는 친구 자체가 안전을 위해 옵셔널을 반환하거든요!
<img width="484" alt="스크린샷 2022-08-22 오후 10 13 00" src="https://user-images.githubusercontent.com/61951603/185929623-7d0cd061-f63c-43b7-a45c-330b7f5a80b3.png">

2022-08-22 21:51 UTC, merged