[FEAT] voicemail ui partly completed
ECube-Reboot/LiveOn-Reborn-iOS pull request #44
Opened 2022-08-25 20:07 UTC by seongmin221

## 🟣 관련 이슈
#18

## 🟣 구현/변경 사항 및 이유
- 일단 음성메세지 ui '만' 구현되었습니다
- 관련 함수들은 구현 중

## 🟣 PR Point
- 후딱 하느라 ui도 아직 불완전한 부분이 있는데 최대한 빨리 고쳐보도록 하겠습니다
- 함수 부분도 지난번에 말씀드린 문제를 아직 해결을 못해서 이 부분도 반영해서 다시 pr 날릴 것 같습니다
- 지금 이상하게도 현재 브랜치에서 디벨롭 풀을 당기면 앱이 터지는 케이스가 계속 생깁니다.... 이건 나중에 모여 있을 때 해결해봐야 할 것 같네요 만약 이 PR을 머지했을 때에도 그런 현상이 발생한다면.... 문제가 생기니 테스트 해 보실 때에도 주의 부탁드립니다...!

## 🟣 참고 사항

2022-08-26 06:26 UTC, italsehf approved these changes
코드 깔끔하게 적어주셔서 이해하기 쉬웠습니다👍
제가 남긴 질문 말고는 딱히 문제되는 부분은 안 보여서 approve 하겠습니다!
통신 관련 코드는 다른 분들이 코드 리뷰 잘 남겨줄라고 믿어요..ㅎㅎ

2022-08-26 06:26 UTC, italsehf commented on liveOnReboot/liveOn/View/Gift/VoiceMail/CreateVoicemailView.swift
> +    @FocusState private var isFocused: Bool
@State 이 아닌 @FocusState는 무슨 차이가 있나요 ??

2022-08-26 08:53 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/VoiceMail/CreateVoicemailView.swift
> +    @FocusState private var isFocused: Bool
오 사실 저도 잘 몰랐는데 구글링해보니까 신기한 기능이 있더라구요

```swift

enum Field: Hashable {
    case username
    case password
}

@FocusState private var focusedField: Field?

var body: some View {
    Form {
        TextField("Username", text: $username)
            .focused($focusedField, equals: .username)

        SecureField("Password", text: $password)
            .focused($focusedField, equals: .password)

        Button("Sign In") {
            if username.isEmpty {
                focusedField = .username
            } else if password.isEmpty {
                focusedField = .password
            } else {
                handleLogin(username, password)
            }
        }
    }
}

```

이런 경우에서 만약 비밀번호나 아이디 둘 중 하나라도 빈 상태로 로그인을 하려고 로그인을 하려고 하면
저절로 빈 곳으로 이동해서 입력하게 할 수 있다네요..!!

2022-08-27 06:41 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/VoiceMail/CreateVoicemailView.swift
> +    @FocusState private var isFocused: Bool
오 쉣 어떤 버튼을 눌렀을 때, 조건에 만족하지 않으면 그 영역으로 이동할 수 있게 할 수 있겠군요! 유용하네요.. 👍

2022-08-27 06:48 UTC, jinccc97 requested changes
수고하셨습니다! 쫌만 더 힘내서 마무리해봐요 :)!!! 이드 새벽 2시의 기적 믿습니다믿어요~

2022-08-27 06:48 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/Gift/VoiceMail/Voicemail.swift
> +//  Voicemail.swift
파일명 변수명과 통일하여 VoiceMail은 어떨까요..? ㅎㅎㅎㅋㅋㅋ

2022-08-27 06:48 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/VoiceMail/VoicemailPopUpView.swift
> +//struct VoicemailPopUpView_Previews: PreviewProvider {
p3;
주석 삭제!

2022-08-27 06:48 UTC, jinccc97 commented on liveOnReboot/liveOn/View/Gift/VoiceMail/VoicemailView.swift
> +            .blur(radius: isShowPopUp ? 6 : 0)
p1;
이거 블러말고 material로 통일부탁드립니다! 
888633aa8beb7d3dcd428aaa7846393cde7c3cb7 의 48번줄
`    .overlay {
      if showDetail {
        if let letter = selectedLetter {
          LetterDetailView(letter: letter)
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
            .background(.ultraThinMaterial)
            .onTapGesture {
              withAnimation {
                showDetail.toggle()
              }
            }
        }
      }
    }`
참고!

2022-08-27 07:16 UTC, italsehf commented on liveOnReboot/liveOn/View/Gift/VoiceMail/CreateVoicemailView.swift
> +    @FocusState private var isFocused: Bool
홀리몰리 하나 배워갑니다👍

2022-08-29 05:23 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/VoiceMail/VoicemailView.swift
> +            .blur(radius: isShowPopUp ? 6 : 0)
반영했슴다!
[5acf36c](https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/44/commits/5acf36c80adf4facbe7a0f59bfa66ff31160f3cd)

2022-08-29 05:30 UTC, jinccc97 commented
앙 수고링

2022-08-29 05:30 UTC, jinccc97 approved these changes
수고했다능~

2022-08-29 06:48 UTC, merged