[FEAT] 애플로그인 및 로그인 api 연동
ECube-Reboot/LiveOn-Reborn-iOS pull request #45
Opened 2022-08-26 02:29 UTC by jola7373

## 🟣 관련 이슈

#24

## 🟣 구현/변경 사항 및 이유
- 애플소셜 로그인
- 로그인 api 연동
- keychain 저장, 삭제, 읽기 구현
- accesstoken및 refreshtoken 키체인에 저장
- 토큰 keychain에서 가져오기

## 🟣 PR Point
- 주석은 빼고 봐주세요! 추후에 자동로그인 로직에 필요할까봐 살려놨어요!
- 그 외의 모든것은 짜잘한것도 말씀해주세요

## 🟣 참고 사항

2022-08-26 03:18 UTC, seongmin221 requested changes
가볍게 바꿀것들 리뷰 남겨뒀습니다!
API 하시느라 수고 많으셨어요!!

2022-08-26 03:18 UTC, seongmin221 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginRequestDTO.swift
> +let accessToken: String
p2;
들여쓰기..!

2022-08-26 03:18 UTC, seongmin221 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginResponseDTO.swift
> +
p2;
필요없는 줄바꿈 없애기!

2022-08-26 03:18 UTC, seongmin221 commented on liveOnReboot/liveOn/Network/Auth/Service/AuthService.swift
>  import Moya
p1;
?? 왜 foundation 이 두번 import 됐나유??

2022-08-26 03:18 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +//                    }
p3;
사용하지 않는 코드인가오??
그렇다면 삭제해주세용~

2022-08-26 03:18 UTC, seongmin221 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +//    }
p1;
사용하지 않는 코드라면 삭제해주세요~

2022-08-26 03:18 UTC, seongmin221 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +}
p1;
여기도 사용하지 않는 코드라면 삭제 부탁드립니다!

2022-08-26 03:22 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +//                    }
오 주석 빼고 보라고 하셨군요 죄송합니다 ㅎㅎ...

2022-08-26 03:22 UTC, seongmin221 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +//    }
ㅎ 여기도

2022-08-26 03:22 UTC, seongmin221 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +}
ㅎㅎ 여기도...

2022-08-27 06:49 UTC, jinccc97 approved these changes
뿌듯하네요 ☺️ 자랑스럽다,,, 수고하셨습니다!

2022-08-27 07:17 UTC, italsehf approved these changes
이드가 요청한 request 얼른 수정하고 빨리 머지해주세요 ~
빨리 써보고 싶어서 못 참는 중

2022-08-28 02:22 UTC, jola7373 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginRequestDTO.swift
> +let accessToken: String
b86ab01ec558ac5c8bbfa3da93e2d738aa511c19 수정 완료!!

2022-08-28 02:22 UTC, jola7373 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginResponseDTO.swift
> +
724a0f03ed0d5de5fd9b573ba690d378241967fd 요것도 수정 완료!

2022-08-28 02:23 UTC, jola7373 commented on liveOnReboot/liveOn/Network/Auth/Service/AuthService.swift
>  import Moya
83a793c0deb8b5d2c2ec6bb247585c5759f1c7e6 삭제했으욥~

2022-08-28 11:19 UTC, Rookie0031 approved these changes
## 고생하셨습니다온!!!!

서버에 스위프트까지 빡셋을텐데 잘해주셧네요 떙큐
로그인 부분은 잘몰라서 자세한 코드리뷰는 힘들었지만 궁금한 점 남겨두었으니 답변주세용 그 후 머지해주시면 될 거 같습니다.

2022-08-28 11:19 UTC, Rookie0031 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +    return "";
## Question
여기에 왜 맨 마지막으로 빈 문자열을 반환하나요??

2022-08-28 11:19 UTC, Rookie0031 commented on liveOnReboot/liveOn/Util/KeyChain.swift
> +        SecItemDelete(query)
## Question
create 함수인데 ItemDelete를 하는 이유는 무엇인가요??

2022-08-28 11:19 UTC, Rookie0031 commented on liveOnReboot/liveOn/ViewModel/SignIn/SignInViewModel.swift
> +        print(KeyChain.read(key: "accessToken")!)
## Question
여기 프린트문은 키체인에 토큰이 있는지 확인하는 용도인가요? 나중에 어떤 코드가 추가되는 부분일까요???

2022-08-28 11:38 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +                            authenticationData = appleSignInViewModel.didFinishAppleSignin(result: result)
## Question
통신 성공하면 authenticationData에 값을 저장해놓는 구조인거 같은데, authenticationData가 어떤건가요??

2022-08-29 01:10 UTC, jola7373 commented on liveOnReboot/liveOn/Util/KeyChain.swift
> +        SecItemDelete(query)
같은 키를 가진 물체가 있을까봐 미리 삭제하고 저장하는거에용

2022-08-29 01:10 UTC, jola7373 commented on liveOnReboot/liveOn/ViewModel/SignIn/SignInViewModel.swift
> +        print(KeyChain.read(key: "accessToken")!)
그냥 확인하는 용도에욥

2022-08-29 01:15 UTC, jola7373 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +    return "";
원래 성공시 토큰 반환로직이었는데 그냥 키체인에 저장하니 return void로 해도 될것 같아요 바꿀께욥

2022-08-29 01:15 UTC, jola7373 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +                            authenticationData = appleSignInViewModel.didFinishAppleSignin(result: result)
원래에는 토큰을 가지고 있는데 사실 이제 로직상 키체인에 저장하니 return void로 바꾸고 authenticationData가 필요없을것 같네요~ 수정하게씁다

2022-08-29 01:21 UTC, jola7373 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +                            authenticationData = appleSignInViewModel.didFinishAppleSignin(result: result)
26a694eb8a5946a47aa46d64b58aea342f6311b0

2022-08-29 01:22 UTC, merged