[Feat] 회원가입 정도에 따른 첫화면 분기처리
ECube-Reboot/LiveOn-Reborn-iOS pull request #47
Opened 2022-08-28 03:00 UTC by jinccc97

## 🟣 관련 이슈
#46 

## 🟣 구현/변경 사항 및 이유
### 1
1레벨 : 애플로그인만
2레벨 : 유저 정보 입력완료
3레벨 : 커플매칭까지 완료 (all finished)
로 구분하여 첫화면이 세팅되게 되었습니다.
### 2
유저정보를 입력하는 api와 연동했습니다.

## 🟣 PR Point
# **이제 pr 올리실 때  liveOnRebootApp()은 올리지 말아주세요!!!**

## 🟣 참고 사항

2022-08-28 03:44 UTC, jola7373 reviewed
부장님 수고많으셨습니다!! 잘 모르겠지만 걍 궁금한거 몇개 물어봤습니다!

2022-08-28 03:44 UTC, jola7373 commented on liveOnReboot/liveOn/Model/SignIn/UserStatus.swift
> +}
생각해보니깐 이 부분은 서버에서 분기처리 하는게 깔끔했을것 같은데 여튼 구현해주셔서 감사합니다~~

2022-08-28 03:44 UTC, jola7373 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +                    }
p5
이건 대체 어느 차이인데 안넘어가는거져?

2022-08-28 03:44 UTC, jola7373 commented on liveOnReboot/liveOn/ViewModel/SignIn/SignInViewModel.swift
> +    }
p4
네트워크에 관련된 성공, 실패에 관련된 분기 처리는 network/service 레이어에서하는게 어떨까요?

2022-08-28 11:37 UTC, Rookie0031 approved these changes
## 고생하셨습니다!!
분기처리 코드가 깔끔하네요 테스트 때도 이상없이 잘작동하던가요??? 특별히 고칠 건 없지만 다온 브랜치와 겹치는 코드가 많은 거 같아 컨플릭이 우려되네요. 만약 그러면 둘이 합의해서 잘 머지하시길^^

2022-08-28 11:37 UTC, Rookie0031 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginResponseDTO.swift
> +    let refreshToken: String
## Question
@jola7373 엑세스 토큰과 리프레시 토큰이 항상 같이 오나요??

2022-08-28 11:37 UTC, Rookie0031 commented on liveOnReboot/liveOn/Model/SignIn/UserStatus.swift
> +        UserDefaults.standard.set(status.rawValue, forKey: "userStatus")
## Question
이전에 특정 key로 저장된 값을 삭제안해도 바로 덮어씌우기도 가능한가요??

2022-08-29 06:57 UTC, seongmin221 requested changes
수고 많으셨습니다!
코드가 잘 이해가 안되서 일단 클린코드만 신경썼어요!
그리고 웬만하면 files changed는 10개 이상 안되도록 부탁드립니다! :)

2022-08-29 06:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginRequestDTO.swift
> +let accessToken: String
p2;
들여쓰기 ㅎㅋ

2022-08-29 06:57 UTC, seongmin221 commented on liveOnReboot/liveOn/Network/Auth/Service/AuthService.swift
>  import Foundation
p1;
Foundation이 두번 import 되어있습니다!
하나 없애주세요!

2022-08-29 06:57 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +                    UserStatus.updateUserStatus(status: UserStatus.appleSignInFinished)
p2;
들여쓰기유

2022-08-29 06:57 UTC, seongmin221 commented on liveOnReboot/liveOn/View/SignIn/InviteCodeView.swift
> +                ShareSheet(activityItems: [ MyActivityItemSource(title: SignInLiteral.inviteCodeShareSheetTitle, text: "\(userData.nickName)\(SignInLiteral.inviteCodeShareSheetText) 초대코드 : [\(code)]"
p2;
계속 들여쓰기만 잡아서 죄송합니다 ㅎ

2022-08-29 06:57 UTC, seongmin221 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +//    }
여기가 이전에 @jola7373 가 나중에 쓸수도 있다고 한 부분이죠?

2022-08-29 06:57 UTC, seongmin221 commented on liveOnReboot/liveOn/ViewModel/SignIn/SignInViewModel.swift
> +                case .success(_):
p2;
success() 안에 input이 필요 없다면 그냥 .success로 써도 됩니다!

2022-08-29 11:21 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +                    }
먼소린지 모르겠지만 이전에는 그냥 애플로그인 버튼 누르면 isActive가 토글되는 식이라 성공여부에 관련없이 넘어갔었지만 얘는 성공하면 토글되게 했습니당.

2022-08-29 16:14 UTC, jola7373 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginResponseDTO.swift
> +    let refreshToken: String
넹넹 기본적으로 로그인을 하는 경우는 사용자가 로그아웃(리프레시 토큰 클라단에 저장되어 있지 않음) 이거나 리프레시 토큰까지 만료 되었을경우만 호출하기 때문에 이 경우에는 같이 옵니다!

2022-08-30 03:53 UTC, jinccc97 commented on liveOnReboot/liveOn/ViewModel/SignIn/SignInViewModel.swift
> +    }
조씁니다! auth에 memeberConfigService에서 유저와 관련된 통신을 처리하도록 할게요

2022-08-30 03:53 UTC, jinccc97 commented on liveOnReboot/liveOn/Model/SignIn/UserStatus.swift
> +        UserDefaults.standard.set(status.rawValue, forKey: "userStatus")
네네!

2022-08-30 03:57 UTC, jinccc97 commented on liveOnReboot/liveOn/ViewModel/SignIn/SignInViewModel.swift
> +                case .success(_):
eb34bd308af21435966b5df3a3d4d201a394aca6

2022-08-30 03:57 UTC, jinccc97 commented on liveOnReboot/liveOn/ViewModel/SignIn/AppleSignInViewModel.swift
> +//    }
예입

2022-08-30 03:57 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SignIn/InviteCodeView.swift
> +                ShareSheet(activityItems: [ MyActivityItemSource(title: SignInLiteral.inviteCodeShareSheetTitle, text: "\(userData.nickName)\(SignInLiteral.inviteCodeShareSheetText) 초대코드 : [\(code)]"
이걸 보네 ;; 감사합니다!
eb34bd308af21435966b5df3a3d4d201a394aca6

2022-08-30 03:57 UTC, jinccc97 commented on liveOnReboot/liveOn/View/SignIn/GettingStartView.swift
> +                    UserStatus.updateUserStatus(status: UserStatus.appleSignInFinished)
eb34bd308af21435966b5df3a3d4d201a394aca6

2022-08-30 03:57 UTC, jinccc97 commented on liveOnReboot/liveOn/Network/Auth/Service/AuthService.swift
>  import Foundation
eb34bd308af21435966b5df3a3d4d201a394aca6

2022-08-30 03:57 UTC, jinccc97 commented on liveOnReboot/liveOn/Network/Auth/DTO/LoginRequestDTO.swift
> +let accessToken: String
eb34bd308af21435966b5df3a3d4d201a394aca6

2022-08-30 05:30 UTC, seongmin221 approved these changes
수고하셨슴다!

2022-08-30 06:06 UTC, merged