[Feat] 꽃관련뷰 UI 작업 일부 완료 & 앱 아이콘 수정
ECube-Reboot/LiveOn-Reborn-iOS pull request #48
Opened 2022-08-28 08:20 UTC by teethemoji

## 🟣 관련 이슈

#14 꽃 선물 보내기

## 🟣 구현/변경 사항 및 이유

담당하고 있는 꽃 관련 뷰 UI 구현 작업을 진행하는 중입니다.

## 🟣 PR Point

- FlowerListView에서 상단 텍스트가 보이지 않는 이슈
- 꽃병에 줄기가 향하도록 rotate할 수 있도록 해야하지만 아직 적용 X
- 꽃 선물 detail 뷰로 들어가면 메시지 내용이 표시되지 않는 이슈
- 앱 아이콘이 작게 축소되었을 때 다소 지저분해 보이는 이슈
- 그 외 다수의 이슈

여러 문제가 있긴 하지만 시간을 너무 오래 끌고 있어 중간 저장 내용을 머지해두려고 PR날립니다.

## 🟣 참고 사항
![image](https://user-images.githubusercontent.com/60784937/187064720-b7f513dc-c1d0-48ef-9478-0bfb3c90f75a.png)

![image](https://user-images.githubusercontent.com/60784937/187064703-e39e19cc-cce2-4b87-9e13-3f0898d33758.png)

2022-08-28 11:46 UTC, Rookie0031 approved these changes
## 고생하셨습니다!!

중간 저장용 머지라고 하시니 바로 어프루브 드리겠습니다
앱 아이콘이 미세하게? 아날로그틱해졌네요 디테일한 작업 감사드립니다

대강의 UI가 마무리되면 그냥 서버통신 진행하시면 됩니다. detail 메시지 내용 표시는 그 과정에서 해결하면 될 거 같네요. 통신부터는 저랑 같이 합시다. 그러니 빨리 UI 마무리해주시길 부탁드립니다^^

2022-08-29 00:09 UTC, italsehf approved these changes
얼른 서버 통신의 세계로 넘어오시죠 !! 
이제 UI는 형태가 드러났으니까 얼른 서버 통신 성공하는 게 우선인 거 같아요🥲

2022-08-29 00:27 UTC, teethemoji commented
> ## 고생하셨습니다!!
> 중간 저장용 머지라고 하시니 바로 어프루브 드리겠습니다 앱 아이콘이 미세하게? 아날로그틱해졌네요 디테일한 작업 감사드립니다
> 
> 대강의 UI가 마무리되면 그냥 서버통신 진행하시면 됩니다. detail 메시지 내용 표시는 그 과정에서 해결하면 될 거 같네요. 통신부터는 저랑 같이 합시다. 그러니 빨리 UI 마무리해주시길!!!

더미데이터의 쪽지 내용도 안 가져와지는데요 ㅋ....
아무튼 서버 연결 작업으로 이동해보겠습니다

2022-08-29 12:35 UTC, seongmin221 requested changes
밀 & 팀 고생 많으셨습니다..!!
가독성 좋게 해주셔서 리뷰 남길게 꽤나 있네요 ㅎㅎ....

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +    @Environment(\.dismiss) private var dismiss
질문입니다!

private을 사용하면 현재 파일에서만 사용할 수 있는걸로 알고 있는데
@Environment를 사용하면 다른 뷰에서도 사용한다는걸 의미하잖아요?!
이렇게 사용해도 문제 없나요??

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                    Circle().fill(.white).frame(width: 160, height: 160, alignment: .center)
p3;
오.. 이거 뒤에 붙는 프로퍼티들 줄바꿈 해주시면 안될까요..

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                        .overlay(Circle().fill(.gray).frame(width: 100, height: 100, alignment: .center).opacity(0.9))
p3;
여기도 줄바꿈 해주시면.... :)

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                                }
p1;
들여쓰기 안맞는거....ㅎ....

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +            Color(uiColor: .systemBackground).opacity(showFlowerPopUp ? 0.8 : 0)
p1;
그그 저도 여기 이전 PR에서 리뷰 받았던 부분인데요
[2bc10b0](https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/commit/2bc10b02910576a910fa48404c66a90d1bfb428b) 의 48번째 줄처럼 material로 통일해주세요!

어떤걸 의미하는지 잘 모르겠으면 
[5acf36c](https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/44/commits/5acf36c80adf4facbe7a0f59bfa66ff31160f3cd)
요게 제가 리뷰 받고 고친 커밋입니다!!

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +struct FlowerPopUpView: View {
p3;
움 FlowerListView와 다른 View에 분리해둬도 좋을 것 같아요!

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                        Image(flowerList[cardIndex].flower!.imageFileName)
p4;
음 여기 꼭 강제언래핑을 해야 하나요??!
무조건 있는 값이 아니라면 굳이 강제언래핑 말고 if let 이나 guard let 사용하면 좋을 듯 합니다!

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +func calculateImageRotationAngle(index: Int) -> Double {
p2;
음 요놈은 꽃들 돌리는 값이라고 이해했는데, 굳이 함수로 둬야 할 필요가 있을까요??
enum으로 사용해도 충분할 것 같아요!

```swift
enum rotationAngle: Int {
    case half = 180
    case none = 0
    case quarterAndHalf = 270
    case quarter = 90
}
```
요런 식으로..??
https://babbab2.tistory.com/116
여기 보면 자세히 나와있는 것 같습니다!

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +func calculateImageRotationAngle(index: Int) -> Double {
p4;
아 그리고 굳이 함수를 extension 밖으로 뺀 이유가 있을까요??
함수 넣어도 잘 되지 않나요?? 저도 잘 모르겠어서..!!

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +func calculateImageRotationAngle(index: Int) -> Double {
p1;
아아ㅏ 그리고 이것도..
제가 전체적으로 적용하는걸 깜빡했는데 ㅎㅎ..
그 현재 파일에서만 사용하는 함수나 변수는 private 붙여주면 좋을 것 같아요!
아마 이 파일에서만 사용하는 함수라는 생각이 들어서 private도 붙여주면 좋을 것 같습니다!

2022-08-29 12:35 UTC, seongmin221 commented on liveOnReboot/liveOn/View/GiftBox/GiftBoxView.swift
> +}
p3;
군데 얘도 extension에 안넣은 이유가 있을까요..?!?!
저 진짜 살짝 헷갈려져서..ㅎ

2022-08-30 15:10 UTC, teethemoji commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +    @Environment(\.dismiss) private var dismiss
이 부분은 다른 분들이 작성하신 코드를 참고해서 작성한 부분이라 작성자분들의 의도를 듣고 싶습니다
@Rookie0031 @jinccc97 @italsehf 어느 분이 작성하셨고 왜 그렇게 하셨는지요???

2022-08-30 15:10 UTC, teethemoji commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                                }
놀랍게도 ctrl + i 해서 나온 결과물이 이것이라는 점.....

2022-08-30 15:21 UTC, teethemoji commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                        Image(flowerList[cardIndex].flower!.imageFileName)
무조건 있는 값인지라 유지하도록 하겠습니다🙃

2022-08-30 16:40 UTC, teethemoji commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +func calculateImageRotationAngle(index: Int) -> Double {
제시해주신 enum으로 처리하는 방법 깔끔하니 좋네요👍
그런데 다시 코드를 읽다보니 이 회전 값이 다양한 곳에서 여러 번 재사용되는 부분이 아니라는 점 && 꽃 병 위에 그리드 형태로 그려지는 꽃 보관함 형태가 아닌 다른 뷰로 변경될 가능성이 높아 사용되지 않을 수도 있다는 점을 고려해 이 부분은 일단 잠시 주석처리 해두겠습니다.

2022-08-30 17:28 UTC, teethemoji commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +            Color(uiColor: .systemBackground).opacity(showFlowerPopUp ? 0.8 : 0)
[207bcdb](https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/48/commits/207bcdb70d99e9dc35d4798d4abdc4b764bcab9d)
수정 완료했습니다

2022-08-30 17:30 UTC, teethemoji commented on liveOnReboot/liveOn/View/GiftBox/GiftBoxView.swift
> +}
extension에 안 넣은 이유 : struct로 따로 뷰들 빼고 그 밑에 필요한 기능을 넣다보니 옮겨야 한다는 것을 잊음
결론 : 수정했습니다 [537f229](https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/48/commits/537f2290101139dc0cacbe9abc59a4e82fcf18bc)

2022-08-30 17:30 UTC, teethemoji commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                        .overlay(Circle().fill(.gray).frame(width: 100, height: 100, alignment: .center).opacity(0.9))
[14c73b4](https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/48/commits/14c73b4d55e19b0803bf13192a7491685c570a9e)
수정 완료

2022-08-30 17:31 UTC, teethemoji commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +                    Circle().fill(.white).frame(width: 160, height: 160, alignment: .center)
[14c73b4](https://github.com/ECube-Reboot/LiveOn-Reborn-iOS/pull/48/commits/14c73b4d55e19b0803bf13192a7491685c570a9e)
수정 완료

2022-08-31 00:27 UTC, italsehf commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +    @Environment(\.dismiss) private var dismiss
이 부분은 구글링을 통해서 코드를 참고하였는데 정확한 이유는 저도 잘 모르겠네요ㅜㅜ

2022-08-31 00:32 UTC, seongmin221 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +    @Environment(\.dismiss) private var dismiss
오호.. 그렇군요,.. 저도 함 구글링 해봐야겠네요🤔

2022-08-31 00:34 UTC, seongmin221 approved these changes
굳굳! 수고하셨습니다!!

2022-08-31 00:42 UTC, Rookie0031 commented on liveOnReboot/liveOn/View/Gift/Flower/FlowerView.swift
> +    @Environment(\.dismiss) private var dismiss
음.. 제가 이해한바로 말씀드리자면..

#### Environment는 EnvironmentObject 와는 다른 property wrapper입니다

기본적으로 개발자들이 선언해주지않아도 view가 가지는 프로퍼티들이 있는데, 그 프로퍼티들에 접근해서 사용한다는 의미입니다.

#### dismiss는 DismissAction이라는 구조체안에 들어있는 함수인데 공식 문서에서 그거 사용하려면 위에 써진 코드대로 사용하라고 권장하고 있습니다.

## Reference
https://developer.apple.com/documentation/swiftui/environment (EnvironmentObject)
https://developer.apple.com/documentation/swiftui/environment (Environment)
https://developer.apple.com/documentation/swiftui/environmentvalues/dismiss (dismiss)

2022-08-31 01:09 UTC, merged